AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Flask en AWS Lambda

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: backend/lambda_handler.lambda_handler
      Runtime: python3.11
      Architectures:
      - arm64
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          STATIC_MODE: 'true'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'secretsmanager:GetSecretValue'
              Resource: 'arn:aws:secretsmanager:us-east-1:369595298303:secret:sapientum_connection-I7Q8Mc'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY