"""1:1 relationship catalog conversation per user

Revision ID: 08209423186a
Revises: 4384d05a3890
Create Date: 2025-05-23 14:15:26.798583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08209423186a'
down_revision = '4384d05a3890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('conversations_catalog_id_key', type_='unique')
        batch_op.create_unique_constraint('unique_user_catalog_conversation', ['speaker_id', 'catalog_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_catalog_conversation', type_='unique')
        batch_op.create_unique_constraint('conversations_catalog_id_key', ['catalog_id'])

    # ### end Alembic commands ###
