"""change users in activity logs

Revision ID: 1750877134
Revises: 7482647e6998
Create Date: 2025-06-25 14:45:55.711795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1750877134'
down_revision = '7482647e6998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activitylogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('other_user_email', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('activitylogs_other_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('activitylogs_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('other_user_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activitylogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('other_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('activitylogs_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('activitylogs_other_user_id_fkey', 'users', ['other_user_id'], ['id'])
        batch_op.drop_column('other_user_email')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
