"""conversation should be related to message

Revision ID: 17d8e1634ec8
Revises: e4c6d67895ac
Create Date: 2025-05-23 09:29:10.736627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d8e1634ec8'
down_revision = 'e4c6d67895ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
