"""add_catalog_editor_flag

Revision ID: 19c16d858e5f
Revises: 38301eea2455
Create Date: 2025-05-12 16:28:59.306126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c16d858e5f'
down_revision = '38301eea2455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_catalog_editor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_catalog_editor')

    # ### end Alembic commands ###
