"""enlarged s3id'


Revision ID: 1d5ff6b8ed25
Revises: 8e0459277b00
Create Date: 2025-05-09 11:33:18.871269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5ff6b8ed25'
down_revision = '8e0459277b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('s3Id',
               existing_type=sa.VARCHAR(length=356),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('s3Id',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=356),
               existing_nullable=True)

    # ### end Alembic commands ###
