backend/migrations/versions/298c75903da2_add_agent_version_id_and_agent_id_to_.py """add_agent_version_id_and_agent_id_to_catalog

Revision ID: 298c75903da2
Revises: 164a45d4f73b
Create Date: 2025-10-03 10:52:19.019157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298c75903da2'
down_revision = '164a45d4f73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_version_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.drop_column('agent_id')
        batch_op.drop_column('agent_version_id')

    # ### end Alembic commands ###
