"""removed s3id from file'


Revision ID: 38301eea2455
Revises: 1d5ff6b8ed25
Create Date: 2025-05-09 14:25:25.605945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38301eea2455'
down_revision = '1d5ff6b8ed25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('s3Id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3Id', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
