"""activity log modified

Revision ID: 4cbdaea36b55
Revises: e444b5bc7dd7
Create Date: 2025-05-30 15:02:54.395780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbdaea36b55'
down_revision = 'e444b5bc7dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    eventtype_enum = sa.Enum('PERMISSION_VIOLATION', 'USER_CREATION', 'USER_DELETION', 'USER_EDITION', 'USER_PERMISSION', 'CATALOG_CREATION', 'CATALOG_EDITION', 'CATALOG_DELETION', 'FILE_UPLOAD', 'FILE_DELETION', 'FILE_VERSION', 'CHAT_INTERACTION', name='eventtype')
    eventtype_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('activitylogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', eventtype_enum, nullable=True))
        batch_op.add_column(sa.Column('message_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('activitylogs_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['message_id'], ['id'])
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activitylogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activitylogs_conversation_id_fkey', 'conversations', ['conversation_id'], ['id'])
        batch_op.drop_column('message_id')
        batch_op.drop_column('event')

    # Drop the enum type
    eventtype_enum = sa.Enum(name='eventtype')
    eventtype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
