"""add_encryption_key_to_messages

Revision ID: 51db5cac3907
Revises: 3e4376a1aa71
Create Date: 2025-10-03 14:29:45.511149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51db5cac3907'
down_revision = '3e4376a1aa71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    # ### end Alembic commands ###
