"""removed redundant permissions

Revision ID: 72b475f7ec7e
Revises: 91158f4c37a8
Create Date: 2025-05-08 15:13:48.291719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b475f7ec7e'
down_revision = '91158f4c37a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('document_access')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_access', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
