"""add convo title

Revision ID: 85556c5c43e6
Revises: 6ed690dcfa2b
Create Date: 2025-05-22 10:56:43.803131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85556c5c43e6'
down_revision = '6ed690dcfa2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=1024), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
