"""version removed on file'


Revision ID: 8e0459277b00
Revises: 0fbb91476285
Create Date: 2025-05-09 11:07:51.932840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0459277b00'
down_revision = '0fbb91476285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.VARCHAR(length=16), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
