"""permission_per_catalog

Revision ID: 91158f4c37a8
Revises: 956ab53e173f
Create Date: 2025-05-08 12:01:59.673955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91158f4c37a8'
down_revision = '956ab53e173f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_users',
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('NOT_ALLOWED', 'READ_ONLY', 'FULL', name='permissiontype'), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('catalog_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_users')
    # ### end Alembic commands ###
