"""file type status

Revision ID: 956ab53e173f
Revises: 88d85d9db43c
Create Date: 2025-05-07 13:47:22.993188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956ab53e173f'
down_revision = '88d85d9db43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
