"""add origin column to message

Revision ID: c17c7789b7f5
Revises: revert_to_uppercase_permissions
Create Date: 2025-07-10 14:51:28.719856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17c7789b7f5'
down_revision = 'revert_to_uppercase_permissions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
