"""add convo model

Revision ID: e4c6d67895ac
Revises: 85556c5c43e6
Create Date: 2025-05-22 11:52:11.447888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c6d67895ac'
down_revision = '85556c5c43e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_catalog_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_speaker_id_fkey', type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('session_id')
        batch_op.drop_column('catalog_id')
        batch_op.drop_column('speaker_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('catalog_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('messages_speaker_id_fkey', 'users', ['speaker_id'], ['id'])
        batch_op.create_foreign_key('messages_catalog_id_fkey', 'catalogs', ['catalog_id'], ['id'])

    op.drop_table('conversations')
    # ### end Alembic commands ###
